lines_per_notch = 3.0
multi_click_window_ms = 400
autoscroll_interval_ms = 25
autoscroll_speed = 1.0

[theme]
background = "#1d1f21"
foreground = "#c5c8c6"
cursor = "#c5c8c6"
dim_strength = 0.66

[theme.palette]
black = "#1d1f21"
red = "#cc6666"
green = "#b5bd68"
yellow = "#f0c674"
blue = "#81a2be"
magenta = "#b294bb"
cyan = "#8abeb7"
white = "#c5c8c6"

bright_black = "#969896"
bright_red = "#cc6666"
bright_green = "#b5bd68"
bright_yellow = "#f0c674"
bright_blue = "#81a2be"
bright_magenta = "#b294bb"
bright_cyan = "#8abeb7"
bright_white = "#ffffff"

[font]
size = 15.0
family = "JetBrainsMonoNF-Regular"
fallback = ["Apple Color Emoji", "Apple Symbols", "Hiragino Sans"]
gamma = 1.7
contrast = 30.0
bold_is_bright = false

[cursor]
hollow_cursor_thickness = 0.1

[shell]
locale = "en_US.UTF-8"
