lines_per_notch = 3.0
multi_click_window_ms = 400
autoscroll_interval_ms = 25
autoscroll_speed = 1.0

[theme]
background = "#18191f"
foreground = "#b8af9e"
cursor = "#e0d6bd"
dim_strength = 0.66

[theme.palette]
black = "#18191f"
red = "#a67476"
green = "#8aa387"
yellow = "#ccb89c"
blue = "#5a6986"
magenta = "#c99aa7"
cyan = "#7aacaa"
white = "#b8af9e"

bright_black = "#3d3e44"
bright_red = "#d6b3bd"
bright_green = "#94ad91"
bright_yellow = "#deb88a"
bright_blue = "#8d9bb3"
bright_magenta = "#b8aad9"
bright_cyan = "#90a0a0"
bright_white = "#e0d6bd"

[font]
size = 15.0
family = "JetBrainsMonoNF-Regular"
fallback = ["Apple Color Emoji", "Apple Symbols", "Hiragino Sans"]
gamma = 1.7
contrast = 30.0
bold_is_bright = false

[cursor]
hollow_cursor_thickness = 0.1

[shell]
locale = "en_US.UTF-8"
